import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',

    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                'on-error-container': '#93000a',
                'on-secondary-fixed-variant': '#444749',
                'surface-dim': '#d4dbe2',
                'inverse-primary': '#b4c5ff',
                'on-primary-fixed-variant': '#003ea8',
                'tertiary-fixed-dim': '#bcc7de',
                'surface': '#f6f9ff',
                'on-secondary-container': '#626567',
                'on-primary': '#ffffff',
                'inverse-on-surface': '#ebf1f9',
                'on-tertiary-fixed-variant': '#3c475a',
                'secondary-fixed-dim': '#c4c7c9',
                'primary-container': '#2563eb',
                'on-tertiary': '#ffffff',
                'surface-variant': '#dde3eb',
                'on-tertiary-fixed': '#111c2d',
                'primary-fixed': '#dbe1ff',
                'on-error': '#ffffff',
                'on-secondary': '#ffffff',
                'outline': '#737686',
                'surface-container': '#e8eef6',
                'outline-variant': '#c3c6d7',
                'secondary-container': '#e0e3e5',
                'tertiary-fixed': '#d8e3fb',
                'inverse-surface': '#2b3137',
                'secondary-fixed': '#e0e3e5',
                'on-background': '#161c22',
                'primary': '#004ac6',
                'on-tertiary-container': '#ecf1ff',
                'surface-tint': '#0053db',
                'on-secondary-fixed': '#191c1e',
                'secondary': '#5c5f61',
                'on-surface-variant': '#434655',
                'primary-fixed-dim': '#b4c5ff',
                'background': '#f6f9ff',
                'surface-container-low': '#eef4fc',
                'on-surface': '#161c22',
                'tertiary': '#4b566a',
                'error': '#ba1a1a',
                'surface-container-highest': '#dde3eb',
                'on-primary-container': '#eeefff',
                'tertiary-container': '#636e83',
                'error-container': '#ffdad6',
                'surface-bright': '#f6f9ff',
                'surface-container-high': '#e3e9f1',
                'on-primary-fixed': '#00174b',
                'surface-container-lowest': '#ffffff',
            },

            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },

            spacing: {
                md: '16px',
                '2xl': '48px',
                lg: '24px',
                sm: '8px',
                xs: '4px',
                '3xl': '64px',
                xl: '32px',
                'container-max': '1280px',
                base: '4px',
                gutter: '24px',
            },

            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                h2: ['Inter'],
                'body-lg': ['Inter'],
                'body-sm': ['Inter'],
                'h1-mobile': ['Inter'],
                h1: ['Inter'],
                'body-md': ['Inter'],
                'label-md': ['Inter'],
                h3: ['Inter'],
                'label-sm': ['Inter'],
            },

            fontSize: {
                h2: ['30px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'h1-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
                h1: ['36px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
                h3: ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
            },
        },
    },

    plugins: [forms],
};
